# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677b3d3cf8a55ebd1f05cc992be6c26534e508a2bbc8e9dadc9db68d03e6ce78c419c92fa8ea15e3fc5c6ec404442f0b19b580609bac080a74f1c7c77c4364ad

test:
  secret_key_base: 02c0c55bc88c75bf775600a37a7491a4285aebc577ac2135a3b37536d52af14ee3a0358d84b2967a2d1181f6530290c05a4d7125f97f6b9c28ef1f0a73bd9529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
